name: tests

on:
  push:
    branches: [main, dev]
  pull_request:
  # allows manual triggering of this workflow
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.4"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Full Python environment cacheing
        # see AI2 blogpost for details: https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: v1-${{ env.pythonLocation }}-${{ hashFiles('backend/requirements/dev.txt') }}-${{ hashFiles('backend/requirements/prod.txt') }}
      - name: Install dependencies with pip
        run: |
          pip install --quiet -r backend/requirements/prod.txt -r backend/requirements/dev.txt

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.4"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Full Python environment cacheing
        # see AI2 blogpost for details: https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: v1-${{ env.pythonLocation }}-${{ hashFiles('backend/requirements/dev.txt') }}-${{ hashFiles('backend/requirements/prod.txt') }}
      - name: Install dependencies with pip
        run: |
          pip install --quiet -r backend/requirements/prod.txt -r backend/requirements/dev.txt
